default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: localhost

development:
  <<: *default
  database: blog_rspec_development

test:
  <<: *default
  database: blog_rspec_test

production:
  <<: *default
  database: blog_rspec_production
  username: blog_rspec
  password: <%= ENV['BLOG_RSPEC_DATABASE_PASSWORD'] %>
